service: sb-omnicore-mcp
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 30
  region: us-west-2
  memorySize: 256
  environment:
    PORTFOLIO_BASE_URL: https://someshbagadiya.dev
    NODE_ENV: production

functions:
  mcpServer:
    handler: build/lambda.handler
    description: 'SB-OMNICORE MCP server for Somesh Bagadiya portfolio'
    events:
      - http:
          path: mcp
          method: post
          cors: true
      - http:
          path: mcp
          method: options
          cors: true

plugins:
  - serverless-offline 